name: Prepare a .zip file with the current state of the plugin
# Inspired by, but not based on https://github.com/WordPress/gutenberg/blob/b89fb7b6eaf619bde0269e2a7fbf6245822f6cbf/.github/workflows/build-plugin-zip.yml#L153

on:
  pull_request:
    paths:
    - 'build/**'
    - 'includes/**'
    - 'languages/**'
    - 'src/**'
    - '${{ github.event.repository.name }}.php'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:

  prepare-plugin-zip:
    name: Checkout current state into zip file
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: wp-cli

      - name: Install latest version of dist-archive-command
        run: wp package install wp-cli/dist-archive-command:dev-main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        # - [Incorrect version number used when creating zip archive · Issue #92 · wp-cli/dist-archive-command](https://github.com/wp-cli/dist-archive-command/issues/92)
        run: |
          npm run build
          wp dist-archive . ./${{ github.event.repository.name }}-pr.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-PR
          path: ./${{ github.event.repository.name }}-pr.zip

  comment-playground-link:
    name: Comment with playground link
    # https://github.com/actions/github-script?tab=readme-ov-file#comment-on-an-issue
    # vs.
    # https://docs.github.com/de/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment--parameters
    needs: prepare-plugin-zip
    runs-on: ubuntu-latest

    # Permission can be added at job level or workflow level
    permissions:
      contents: write   # This is required to create/push the new git tag

    steps:
      - name: Add comment (& log context attributes)
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 (Not, yet) A link to a *WordPress playground* instance with your least recent changes to GatherPress.'
            })
