name: Generate Playground Assets

on:
  # push:
  workflow_dispatch:

jobs:
  generate-playground-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GatherPress & Clone sourcecode.
        uses: actions/checkout@v4
        with:
          path: 'wp-content/plugins/gatherpress'
          ref: main

      - name: Clone GatherPress demo-data.
        uses: actions/checkout@v4
        with:
          repository: 'carstingaxion/gatherpress-demo-data'
          path: 'wp-content/uploads/gatherpress-demo-data'
          ref: main

      - name: Copy built assets into ZIP for extraction inside Playground.
        run: |
          zip -FSr zips/playground-assets.zip wp-content -x "*.git*" "*.mp4*" "*/jetpack/"
          rm -rf wp-content

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Persist prepared assets'
